/*
* @author Namir Hassan
* @date 11/17/17
* @name Programming Assignment 7
*/

#include "emergency.h"


int main() {

	newArrival("a", 3);
	newArrival("b", 4);
	newArrival("c", 7);
	newArrival("c4", 1);
	newArrival("d", 10);
	newArrival("cc", 11);
	newArrival("dd", 30);
	newArrival("e", 40);
	newArrival("f", 41);
	newArrival("g", 60);
	newArrival("h", 61);
	newArrival("i", 66);
	newArrival("j", 71);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();

	//Round - 1
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("c2", 71);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("d2", 91);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("c31", 63);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("d31", 33);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();

	//Round - 1
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("c3", 2);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("d3", 93);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("d4", 65);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("c22", 1);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("c23", 1);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	newArrival("d22", 1);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	getNextPatient();
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();

	newArrival("a", 85);
	newArrival("b", 94);
	newArrival("c", 97);
	newArrival("c4", 81);
	newArrival("d", 79);
	newArrival("cc", 88);
	newArrival("dd", 90);
	newArrival("e", 80);
	newArrival("f", 41);
	newArrival("g", 66);
	newArrival("h", 61);
	newArrival("i", 67);
	newArrival("j", 71);
	printf("Current TIme: %d\t", getCurrentTime());
	printItems();
	maxprintItems();
	queueprintItems();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	newArrival("c4", 81);
	newArrival("d", 79);
	newArrival("cc", 88);
	newArrival("dd", 90);
	newArrival("e", 80);
	newArrival("f", 41);
	newArrival("g", 66);
	newArrival("h", 61);
	newArrival("i", 67);
	queueprintItems();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	queueprintItems();
	queueprintItems();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	queueprintItems();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	queueprintItems();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();
	getNextPatient();

	return 0;
}
